#!/usr/bin/env node

import inquirer from 'inquirer';
import fs from 'fs-extra';
import path from 'path';
import { fileURLToPath } from 'url';
import chalk from 'chalk';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

interface ProjectInfo {
  projectName: string;
  description: string;
  author: string;
  agentPurpose: string;
}

async function welcome(): Promise<void> {
  console.log(chalk.cyan(`
╔═══════════════════════════════════════════════════════╗
║             Welcome to agent-init!                   ║
║   Set up your agent-repo with opinionated defaults    ║
╚═══════════════════════════════════════════════════════╝
  `));
}

async function gatherInfo(): Promise<ProjectInfo> {
  const projectName = path.basename(process.cwd());

  const answers = await inquirer.prompt<ProjectInfo>([
    {
      type: 'input',
      name: 'projectName',
      message: 'Project name:',
      default: projectName,
      validate: (input: string) => input.length > 0 || 'Project name is required'
    },
    {
      type: 'input',
      name: 'description',
      message: 'Project description:',
      default: 'An agent-powered project'
    },
    {
      type: 'input',
      name: 'author',
      message: 'Author name:',
      default: process.env.USER || 'Anonymous'
    },
    {
      type: 'input',
      name: 'agentPurpose',
      message: 'What is the primary purpose of your agent?',
      default: 'Assist with development tasks'
    }
  ]);

  return answers;
}

async function createFiles(data: ProjectInfo): Promise<void> {
  const projectDir = process.cwd();

  console.log(chalk.cyan('\n📁 Creating project structure...\n'));

  await fs.ensureDir(path.join(projectDir, '.agents'));
  await fs.ensureDir(path.join(projectDir, '.agents/prompts'));
  await fs.ensureDir(path.join(projectDir, '.agents/config'));

  await fs.writeFile(
    path.join(projectDir, 'README.md'),
    `# ${data.projectName}

${data.description}

## Overview

This is an agent-powered repository. The agents in this project are configured to help with ${data.agentPurpose}.

## Agents

See [agents.md](./agents.md) for agent definitions and capabilities.

## Worklog

See [worklog.md](./worklog.md) for a log of work completed.

## Quick Start

1. Review [agents.md](./agents.md) to understand your agents
2. Check [worklog.md](./worklog.md) for current status
3. Start working with your agent

## Project Info

- **Author**: ${data.author}
- **Created**: ${new Date().toISOString().split('T')[0]}
`
  );

  await fs.writeFile(
    path.join(projectDir, 'agents.md'),
    `# Agents

This document defines the agents configured for this project.

## Primary Agent

**Purpose**: ${data.agentPurpose}

### Capabilities

- Task automation and execution
- File creation and modification
- Code analysis and review
- Documentation generation

### Configuration

Agent configuration is stored in \`.agents/config/\`.

## Agent Registry

| Agent | Role | Status |
|-------|------|--------|
| primary | Main assistant | active |

## Conventions

- All agent prompts are stored in \`.agents/prompts/\`
- Agent configurations are in \`.agents/config/\`
- Agent work is logged in \`worklog.md\`

---

*This file is auto-generated by agent-init*
`
  );

  await fs.writeFile(
    path.join(projectDir, 'worklog.md'),
    `# Worklog

A log of work completed by agents in this project.

---

## ${new Date().toISOString().split('T')[0]}

### Initialized

- Project initialized with agent-init
- Primary agent configured for: ${data.agentPurpose}

---

*This file is auto-generated by agent-init*
`
  );

  const agentConfig = {
    name: 'primary',
    purpose: data.agentPurpose,
    created: new Date().toISOString(),
    settings: {
      model: 'default',
      temperature: 0.7,
      maxTokens: 4096
    }
  };

  await fs.writeFile(
    path.join(projectDir, '.agents/config/primary.json'),
    JSON.stringify(agentConfig, null, 2)
  );

  await fs.writeFile(
    path.join(projectDir, '.agents/prompts/system.md'),
    `# System Prompt

You are a helpful AI agent assisting with: ${data.agentPurpose}

## Guidelines

- Be concise and practical
- Prefer clear explanations over complex solutions
- Log significant actions in worklog.md
- Follow project conventions

## Working with Files

- Read before writing
- Preserve existing code style
- Add comments for non-obvious logic
`
  );

  await fs.writeFile(
    path.join(projectDir, '.gitignore'),
    `node_modules/
.DS_Store
*.log
.env
`
  );
}

async function showSummary(): Promise<void> {
  const projectDir = process.cwd();
  const files = await fs.readdir(projectDir);
  const mdFiles = files.filter(f => f.endsWith('.md'));
  const agentFiles = await fs.readdir(path.join(projectDir, '.agents'), { recursive: true });

  console.log(chalk.green(`
╔═══════════════════════════════════════════════════════╗
║                  Setup Complete!                     ║
╚═══════════════════════════════════════════════════════╝
  `));

  console.log(chalk.cyan('Files created:\n'));
  console.log(chalk.white('  📄 ' + mdFiles.join('\n  📄 ')));
  console.log(chalk.white('  📁 .agents/\n'));

  console.log(chalk.yellow('Next steps:\n'));
  console.log(chalk.white(`  1. Review agents.md to understand your agents`));
  console.log(chalk.white(`  2. Check worklog.md for current status`));
  console.log(chalk.white(`  3. Customize .agents/prompts/system.md\n`));
}

export async function init(): Promise<void> {
  await welcome();
  const info = await gatherInfo();
  await createFiles(info);
  await showSummary();
}

init().catch(console.error);