#!/usr/bin/env node

import inquirer from 'inquirer';
import fs from 'fs-extra';
import path from 'path';
import { fileURLToPath } from 'url';
import chalk from 'chalk';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

interface ProjectInfo {
  projectName: string;
  projectPath: string;
  projectAbout: string;
  author: string;
}

async function welcome(): Promise<void> {
  console.log(chalk.cyan(`
╔═══════════════════════════════════════════════════════╗
║             Welcome to agent-init!                   ║
║   Set up your agent-repo with opinionated defaults    ║
╚═══════════════════════════════════════════════════════╝
  `));
}

async function gatherInfo(): Promise<ProjectInfo> {
  const initial = await inquirer.prompt<{ projectName: string }>([
    {
      type: 'input',
      name: 'projectName',
      message: 'Project name:',
      default: 'my-agent-project',
      validate: (input: string) => {
        if (!input.trim()) return 'Project name is required';
        if (/[<>:"/\\|?*]/.test(input)) return 'Invalid characters in project name';
        return true;
      }
    }
  ]);

  const projectPath = path.resolve(process.cwd(), initial.projectName);

  if (await fs.pathExists(projectPath)) {
    const { overwrite } = await inquirer.prompt<{ overwrite: boolean }>([
      {
        type: 'confirm',
        name: 'overwrite',
        message: `Directory "${initial.projectName}" already exists. Continue?`,
        default: false
      }
    ]);
    if (!overwrite) {
      console.log(chalk.yellow('Aborted.'));
      process.exit(0);
    }
  } else {
    await fs.ensureDir(projectPath);
  }

  const answers = await inquirer.prompt<Omit<ProjectInfo, 'projectName' | 'projectPath'>>([
    {
      type: 'input',
      name: 'projectAbout',
      message: 'What is this project about? (optional)',
      default: ''
    },
    {
      type: 'input',
      name: 'author',
      message: 'Author name:',
      default: process.env.USER || 'Anonymous'
    }
  ]);

  return {
    projectName: initial.projectName,
    projectPath,
    projectAbout: answers.projectAbout || 'General purpose agent-ready project',
    author: answers.author
  };
}

export async function createFiles(data: ProjectInfo): Promise<void> {
  const projectDir = data.projectPath;

  console.log(chalk.cyan('\n📁 Creating project structure...\n'));

  await fs.ensureDir(path.join(projectDir, '.agents'));
  await fs.ensureDir(path.join(projectDir, '.agents/prompts'));
  await fs.ensureDir(path.join(projectDir, '.agents/config'));

  await fs.writeFile(
    path.join(projectDir, 'README.md'),
    `# ${data.projectName}

${data.projectAbout}

## Overview

This is an agent-powered repository. The agents in this project are configured to help with ${data.projectAbout}.

## Agents

See [agents.md](./agents.md) for agent definitions and capabilities.

## Worklog

See [worklog.md](./worklog.md) for a log of work completed.

## Quick Start

1. Review [agents.md](./agents.md) to understand your agents
2. Check [worklog.md](./worklog.md) for current status
3. Start working with your agent

## Project Info

- **Author**: ${data.author}
- **Created**: ${new Date().toISOString().split('T')[0]}
`
  );

  const templateDir = path.join(__dirname, '..', 'templates');
  const agentsTemplate = await fs.readFile(
    path.join(templateDir, 'AGENTS.md.template'),
    'utf-8'
  );

  await fs.writeFile(
    path.join(projectDir, 'agents.md'),
    agentsTemplate.replace('{{projectAbout}}', data.projectAbout)
  );

  await fs.writeFile(
    path.join(projectDir, 'worklog.md'),
    `# Worklog

A log of work completed by agents in this project.

---

## ${new Date().toISOString().split('T')[0]}

### Initialized

- Project initialized with agent-init
- Primary agent configured for: ${data.projectAbout}

---

*This file is auto-generated by agent-init*
`
  );

  const agentConfig = {
    name: 'primary',
    purpose: data.projectAbout,
    created: new Date().toISOString(),
    settings: {
      model: 'default',
      temperature: 0.7,
      maxTokens: 4096
    }
  };

  await fs.writeFile(
    path.join(projectDir, '.agents/config/primary.json'),
    JSON.stringify(agentConfig, null, 2)
  );

  await fs.writeFile(
    path.join(projectDir, '.agents/prompts/system.md'),
    `# System Prompt

You are a helpful AI agent assisting with: ${data.projectAbout}

## Guidelines

- Be concise and practical
- Prefer clear explanations over complex solutions
- Log significant actions in worklog.md
- Follow project conventions

## Working with Files

- Read before writing
- Preserve existing code style
- Add comments for non-obvious logic
`
  );

  await fs.writeFile(
    path.join(projectDir, '.gitignore'),
    `node_modules/
.DS_Store
*.log
.env
`
  );
}

async function showSummary(projectPath: string, projectName: string): Promise<void> {
  const files = await fs.readdir(projectPath);
  const mdFiles = files.filter(f => f.endsWith('.md'));

  console.log(chalk.green(`
╔═══════════════════════════════════════════════════════╗
║                  Setup Complete!                     ║
╚═══════════════════════════════════════════════════════╝
  `));

  console.log(chalk.cyan(`Project created at: ${projectPath}\n`));
  console.log(chalk.cyan('Files created:\n'));
  console.log(chalk.white('  📄 ' + mdFiles.join('\n  📄 ')));
  console.log(chalk.white('  📁 .agents/\n'));

  console.log(chalk.yellow('Next steps:\n'));
  console.log(chalk.white(`  1. cd ${projectName}`));
  console.log(chalk.white(`  2. Review agents.md to understand your agents`));
  console.log(chalk.white(`  3. Check worklog.md for current status`));
  console.log(chalk.white(`  4. Customize .agents/prompts/system.md\n`));
}

export async function init(): Promise<void> {
  await welcome();
  const info = await gatherInfo();
  await createFiles(info);
  await showSummary(info.projectPath, info.projectName);
}

init().catch(console.error);